import type { Locale } from "@/lib/i18n"
export const THEME_THREE_HOME_COPY = {
  zh: {
    title: "给自己，一点游戏时间", subtitle: "游戏、专注训练和实用工具，都在这里。",
    navigation: "主题三主导航", home: "首页", games: "游戏库", tools: "工具",
    search: "搜索游戏或工具", placeholder: "搜索游戏或工具", clear: "清除搜索",
    library: "挑一款，慢慢玩", libraryDescription: "一场对弈，一点挑战，或者纯粹的放松。",
    toolsTitle: "趁手工具", toolsDescription: "让琐事简单一点，给自己多一点时间。",
    all: "全部", results: "个匹配结果", searchResults: "搜索结果",
    empty: "暂时没有找到", emptyHint: "换个关键词，或清除搜索查看全部内容。",
    featured: "精选游戏", start: "开始游戏", tilesDescription: "合并数字，挑战下一步",
    gomokuDescription: "黑白之间，智取全局", snakeDescription: "经典玩法，越吃越长",
    text: "文本整理", textDescription: "高效处理文本内容", anime: "追番助手", animeDescription: "管理你的追番清单",
  },
  en: {
    title: "A little time to play", subtitle: "Games, focus exercises and useful tools. All in one place.",
    navigation: "Theme Three navigation", home: "Home", games: "Library", tools: "Tools",
    search: "Search games or tools", placeholder: "Search games or tools", clear: "Clear search",
    library: "Find your next game", libraryDescription: "A friendly match, a challenge, or a moment to unwind.",
    toolsTitle: "Handy tools", toolsDescription: "Simplify the little things. Make more time for yourself.",
    all: "All", results: "matches", searchResults: "Search results",
    empty: "Nothing here just yet", emptyHint: "Try another keyword, or clear your search to see everything.",
    featured: "Featured game", start: "Play now", tilesDescription: "Merge numbers. Find your next move.",
    gomokuDescription: "Black, white, and your next move.", snakeDescription: "A classic. Eat, grow, repeat.",
    text: "Text cleanup", textDescription: "Put your words in order", anime: "Anime tracker", animeDescription: "Keep track of your watchlist",
  },
  th: {
    title: "ให้เวลากับการเล่นสักนิด", subtitle: "เกม ฝึกสมาธิ และเครื่องมือที่มีประโยชน์ รวมไว้ที่เดียว",
    navigation: "การนำทางธีม 3", home: "หน้าแรก", games: "คลังเกม", tools: "เครื่องมือ",
    search: "ค้นหาเกมหรือเครื่องมือ", placeholder: "ค้นหาเกมหรือเครื่องมือ", clear: "ล้างการค้นหา",
    library: "เลือกเกม แล้วค่อย ๆ เล่น", libraryDescription: "ประลองฝีมือ ท้าทายตัวเอง หรือผ่อนคลายสักหน่อย",
    toolsTitle: "เครื่องมือใกล้มือ", toolsDescription: "จัดการเรื่องเล็ก ๆ ให้เรียบง่าย มีเวลาให้ตัวเองมากขึ้น",
    all: "ทั้งหมด", results: "ผลลัพธ์", searchResults: "ผลการค้นหา",
    empty: "ยังไม่พบรายการที่ตรงกัน", emptyHint: "ลองคำค้นอื่น หรือล้างการค้นหาเพื่อดูทั้งหมด",
    featured: "เกมแนะนำ", start: "เริ่มเล่น", tilesDescription: "รวมตัวเลข ค้นหาตาถัดไป",
    gomokuDescription: "ดำและขาว วางแผนเพื่อชัยชนะ", snakeDescription: "เกมคลาสสิก กินแล้วเติบโต",
    text: "จัดข้อความ", textDescription: "จัดการข้อความให้เป็นระเบียบ", anime: "ติดตามอนิเมะ", animeDescription: "จัดการรายการที่คุณติดตาม",
  },
} satisfies Record<Locale, Record<string, string>>
